name: build-runner

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup build tools
        uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-architecture: x64

      - name: Setup NuGet
        uses: nuget/setup-nuget@v2

      # Optional: bump the patch version number automatically if not manually updated
      - name: Increment version in Directory.Build.props
        shell: pwsh
        run: |
          $file = "Directory.Build.props"
          if (Test-Path $file) {
            (Get-Content $file) | ForEach-Object {
              $m = [regex]::match($_, '<Version>(\d+)\.(\d+)\.(\d+)</Version>')
              if ($m.Success) {
                $newPatch = [int]$m.Groups[3].Value + 1
                $_ -replace $m.Value, "<Version>$($m.Groups[1]).$($m.Groups[2]).$newPatch</Version>"
              } else { $_ }
            } | Set-Content $file
          }

      - name: Restore solution packages
        run: nuget restore LibreHardwareMonitor.sln

      - name: Build application (x64)
        run: msbuild LibreHardwareMonitor\LibreHardwareMonitor.csproj /p:Configuration=Release /p:Platform=x64 /m

      - name: Build library (x64)
        run: msbuild LibreHardwareMonitorLib\LibreHardwareMonitorLib.csproj /p:Configuration=Release /p:Platform=x64 /m

      - name: Package build output
        shell: pwsh
        run: |
          mkdir output
          Copy-Item -Recurse "LibreHardwareMonitor\bin\x64\Release\*" output\
          Copy-Item -Recurse "LibreHardwareMonitorLib\bin\x64\Release\*" output\
          Compress-Archive -Path output\* -DestinationPath LibreHardwareMonitor_build.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: LibreHardwareMonitor-build-${{ github.run_number }}
          path: LibreHardwareMonitor_build.zip
