name: build-runner

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup NuGet
        uses: nuget/setup-nuget@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-architecture: x64

      - name: Increment version
        run: |
          (Get-Content Directory.Build.props) | % {
            $m = [regex]::match($_, '<Version>(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-[^<]*)?</Version>');
            if($m.Success) {
              $new = "<Version>{0}.{1}.{2}-f1arcade.{3}</Version>" -f $m.Groups[1].Value,$m.Groups[2].Value,([int]$m.Groups[3].Value+1),$env:GITHUB_RUN_NUMBER;
              $_ -replace $m.Value, $new
            } else { $_ }
          } | Set-Content Directory.Build.props

      - name: Restore dependencies
        run: nuget restore LibreHardwareMonitor.sln

      - name: Build application (x64)
        run: msbuild LibreHardwareMonitor\LibreHardwareMonitor.csproj /p:Configuration=Release /p:Platform=x64

      - name: Build library (x64)
        run: msbuild LibreHardwareMonitorLib\LibreHardwareMonitorLib.csproj /p:Configuration=Release /p:Platform=x64

      - name: Package build output
        run: |
          mkdir output
          Copy-Item -Recurse LibreHardwareMonitor\bin\Release\net472\* output\
          Compress-Archive -Path output\* -DestinationPath LibreHardwareMonitor_build.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: LibreHardwareMonitor-build
          path: LibreHardwareMonitor_build.zip
